using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Pbz_extractor
{
    class PebbleManifest
    {
        public long manifestVersion;
        public PebbleFirmware firmware;
        public PebbleApplication application;
        public string generatedBy;
        public long generatedAt;
        public PebbleDebug debug;
        public PebbleResourceInfo resources;
        public string type;

        public void Print()
        {
            Console.WriteLine("Pebble Manifest File, version {0}, type {1}", manifestVersion, type);
            Console.WriteLine("Generated by {0}, at {1}", generatedBy, Tool.intToDate(generatedAt));

            if (firmware != null)
            {
                Console.WriteLine("==========");
                firmware.Print();
                Console.WriteLine("==========");
            }

            debug.Print();
            resources.Print();
        }
    }
}
